var hierarchy =
[
    [ "uv::adopt_ref_t", "structuv_1_1adopt__ref__t.html", null ],
    [ "uv::aligned_storage< _LEN_, _ALIGN_ >", "classuv_1_1aligned__storage.html", null ],
    [ "uv::any_ptr", "classuv_1_1any__ptr.html", null ],
    [ "uv::buffer", "classuv_1_1buffer.html", null ],
    [ "uv::default_delete< _T_ >", "structuv_1_1default__delete.html", null ],
    [ "uv::default_destroy< _T_ >", "structuv_1_1default__destroy.html", null ],
    [ "uv::handle", "classuv_1_1handle.html", [
      [ "uv::async", "classuv_1_1async.html", null ],
      [ "uv::check", "classuv_1_1check.html", null ],
      [ "uv::fs_event", "classuv_1_1fs__event.html", null ],
      [ "uv::idle", "classuv_1_1idle.html", null ],
      [ "uv::io", "classuv_1_1io.html", [
        [ "uv::file", "classuv_1_1file.html", null ],
        [ "uv::stream", "classuv_1_1stream.html", [
          [ "uv::pipe", "classuv_1_1pipe.html", null ],
          [ "uv::tcp", "classuv_1_1tcp.html", null ],
          [ "uv::tty", "classuv_1_1tty.html", null ]
        ] ],
        [ "uv::udp", "classuv_1_1udp.html", null ]
      ] ],
      [ "uv::poll", "classuv_1_1poll.html", null ],
      [ "uv::prepare", "classuv_1_1prepare.html", null ],
      [ "uv::process", "classuv_1_1process.html", null ],
      [ "uv::signal", "classuv_1_1signal.html", null ],
      [ "uv::timer", "classuv_1_1timer.html", null ]
    ] ],
    [ "uv::udp::io_info", "structuv_1_1udp_1_1io__info.html", null ],
    [ "uv::is_convertible_to_one_of< _T_, _Ts_ >", "structuv_1_1is__convertible__to__one__of.html", null ],
    [ "uv::is_one_of< _T_, _Ts_ >", "structuv_1_1is__one__of.html", null ],
    [ "uv::loop", "classuv_1_1loop.html", null ],
    [ "uv::mutex", "classuv_1_1mutex.html", null ],
    [ "uv::ref_count", "classuv_1_1ref__count.html", null ],
    [ "uv::ref_guard< _T_ >", "classuv_1_1ref__guard.html", null ],
    [ "uv::request", "classuv_1_1request.html", [
      [ "uv::connect", "classuv_1_1connect.html", null ],
      [ "uv::fs", "classuv_1_1fs.html", [
        [ "uv::fs::access", "classuv_1_1fs_1_1access.html", null ],
        [ "uv::fs::chmod", "classuv_1_1fs_1_1chmod.html", null ],
        [ "uv::fs::chown", "classuv_1_1fs_1_1chown.html", null ],
        [ "uv::fs::close", "classuv_1_1fs_1_1close.html", null ],
        [ "uv::fs::link", "classuv_1_1fs_1_1link.html", null ],
        [ "uv::fs::mkdir", "classuv_1_1fs_1_1mkdir.html", null ],
        [ "uv::fs::mkdtemp", "classuv_1_1fs_1_1mkdtemp.html", null ],
        [ "uv::fs::read", "classuv_1_1fs_1_1read.html", null ],
        [ "uv::fs::readlink", "classuv_1_1fs_1_1readlink.html", null ],
        [ "uv::fs::realpath", "classuv_1_1fs_1_1realpath.html", null ],
        [ "uv::fs::rename", "classuv_1_1fs_1_1rename.html", null ],
        [ "uv::fs::rmdir", "classuv_1_1fs_1_1rmdir.html", null ],
        [ "uv::fs::scandir", "classuv_1_1fs_1_1scandir.html", null ],
        [ "uv::fs::sendfile", "classuv_1_1fs_1_1sendfile.html", null ],
        [ "uv::fs::stat", "classuv_1_1fs_1_1stat.html", null ],
        [ "uv::fs::sync", "classuv_1_1fs_1_1sync.html", null ],
        [ "uv::fs::truncate", "classuv_1_1fs_1_1truncate.html", null ],
        [ "uv::fs::unlink", "classuv_1_1fs_1_1unlink.html", null ],
        [ "uv::fs::utime", "classuv_1_1fs_1_1utime.html", null ],
        [ "uv::fs::write", "classuv_1_1fs_1_1write.html", null ]
      ] ],
      [ "uv::getaddrinfo", "classuv_1_1getaddrinfo.html", null ],
      [ "uv::getnameinfo", "classuv_1_1getnameinfo.html", null ],
      [ "uv::output", "classuv_1_1output.html", null ],
      [ "uv::shutdown", "classuv_1_1shutdown.html", null ],
      [ "uv::udp_send", "classuv_1_1udp__send.html", null ],
      [ "uv::work< _Result_ >", "classuv_1_1work.html", null ],
      [ "uv::write", "classuv_1_1write.html", null ]
    ] ],
    [ "uv::spinlock", "classuv_1_1spinlock.html", null ],
    [ "uv::type_at< _index_, _Ts_ >", "structuv_1_1type__at.html", null ],
    [ "uv::type_storage< _T_ >", "classuv_1_1type__storage.html", null ],
    [ "uv::type_storage< std::function >", "classuv_1_1type__storage.html", null ],
    [ "uv::union_storage< _Ts_ >", "classuv_1_1union__storage.html", null ],
    [ "uv::buffer::instance::uv_buf", "structuv_1_1buffer_1_1instance_1_1uv__buf.html", null ],
    [ "uv::uv_handle_traits< uv_async_t >", "structuv_1_1uv__handle__traits_3_01uv__async__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_check_t >", "structuv_1_1uv__handle__traits_3_01uv__check__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_fs_event_t >", "structuv_1_1uv__handle__traits_3_01uv__fs__event__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_fs_poll_t >", "structuv_1_1uv__handle__traits_3_01uv__fs__poll__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_handle_t >", "structuv_1_1uv__handle__traits_3_01uv__handle__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_idle_t >", "structuv_1_1uv__handle__traits_3_01uv__idle__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_pipe_t >", "structuv_1_1uv__handle__traits_3_01uv__pipe__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_poll_t >", "structuv_1_1uv__handle__traits_3_01uv__poll__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_prepare_t >", "structuv_1_1uv__handle__traits_3_01uv__prepare__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_process_t >", "structuv_1_1uv__handle__traits_3_01uv__process__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_signal_t >", "structuv_1_1uv__handle__traits_3_01uv__signal__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_stream_t >", "structuv_1_1uv__handle__traits_3_01uv__stream__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_tcp_t >", "structuv_1_1uv__handle__traits_3_01uv__tcp__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_timer_t >", "structuv_1_1uv__handle__traits_3_01uv__timer__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_tty_t >", "structuv_1_1uv__handle__traits_3_01uv__tty__t_01_4.html", null ],
    [ "uv::uv_handle_traits< uv_udp_t >", "structuv_1_1uv__handle__traits_3_01uv__udp__t_01_4.html", null ],
    [ "uv::uv_req_traits< uv_connect_t >", "structuv_1_1uv__req__traits_3_01uv__connect__t_01_4.html", null ],
    [ "uv::uv_req_traits< uv_fs_t >", "structuv_1_1uv__req__traits_3_01uv__fs__t_01_4.html", null ],
    [ "uv::uv_req_traits< uv_getaddrinfo_t >", "structuv_1_1uv__req__traits_3_01uv__getaddrinfo__t_01_4.html", null ],
    [ "uv::uv_req_traits< uv_getnameinfo_t >", "structuv_1_1uv__req__traits_3_01uv__getnameinfo__t_01_4.html", null ],
    [ "uv::uv_req_traits< uv_req_t >", "structuv_1_1uv__req__traits_3_01uv__req__t_01_4.html", null ],
    [ "uv::uv_req_traits< uv_shutdown_t >", "structuv_1_1uv__req__traits_3_01uv__shutdown__t_01_4.html", null ],
    [ "uv::uv_req_traits< uv_udp_send_t >", "structuv_1_1uv__req__traits_3_01uv__udp__send__t_01_4.html", null ],
    [ "uv::uv_req_traits< uv_work_t >", "structuv_1_1uv__req__traits_3_01uv__work__t_01_4.html", null ],
    [ "uv::uv_req_traits< uv_write_t >", "structuv_1_1uv__req__traits_3_01uv__write__t_01_4.html", null ]
];