var namespaceuv =
[
    [ "adopt_ref_t", "structuv_1_1adopt__ref__t.html", "structuv_1_1adopt__ref__t" ],
    [ "aligned_storage", "classuv_1_1aligned__storage.html", "classuv_1_1aligned__storage" ],
    [ "any_ptr", "classuv_1_1any__ptr.html", "classuv_1_1any__ptr" ],
    [ "async", "classuv_1_1async.html", "classuv_1_1async" ],
    [ "buffer", "classuv_1_1buffer.html", "classuv_1_1buffer" ],
    [ "check", "classuv_1_1check.html", "classuv_1_1check" ],
    [ "connect", "classuv_1_1connect.html", "classuv_1_1connect" ],
    [ "default_delete", "structuv_1_1default__delete.html", "structuv_1_1default__delete" ],
    [ "default_destroy", "structuv_1_1default__destroy.html", "structuv_1_1default__destroy" ],
    [ "file", "classuv_1_1file.html", "classuv_1_1file" ],
    [ "fs", "classuv_1_1fs.html", "classuv_1_1fs" ],
    [ "fs_event", "classuv_1_1fs__event.html", "classuv_1_1fs__event" ],
    [ "getaddrinfo", "classuv_1_1getaddrinfo.html", "classuv_1_1getaddrinfo" ],
    [ "getnameinfo", "classuv_1_1getnameinfo.html", "classuv_1_1getnameinfo" ],
    [ "handle", "classuv_1_1handle.html", "classuv_1_1handle" ],
    [ "idle", "classuv_1_1idle.html", "classuv_1_1idle" ],
    [ "io", "classuv_1_1io.html", "classuv_1_1io" ],
    [ "is_convertible_to_one_of", "structuv_1_1is__convertible__to__one__of.html", null ],
    [ "is_one_of", "structuv_1_1is__one__of.html", null ],
    [ "loop", "classuv_1_1loop.html", "classuv_1_1loop" ],
    [ "mutex", "classuv_1_1mutex.html", "classuv_1_1mutex" ],
    [ "output", "classuv_1_1output.html", "classuv_1_1output" ],
    [ "pipe", "classuv_1_1pipe.html", "classuv_1_1pipe" ],
    [ "poll", "classuv_1_1poll.html", "classuv_1_1poll" ],
    [ "prepare", "classuv_1_1prepare.html", "classuv_1_1prepare" ],
    [ "process", "classuv_1_1process.html", "classuv_1_1process" ],
    [ "ref_count", "classuv_1_1ref__count.html", "classuv_1_1ref__count" ],
    [ "ref_guard", "classuv_1_1ref__guard.html", "classuv_1_1ref__guard" ],
    [ "request", "classuv_1_1request.html", "classuv_1_1request" ],
    [ "shutdown", "classuv_1_1shutdown.html", "classuv_1_1shutdown" ],
    [ "signal", "classuv_1_1signal.html", "classuv_1_1signal" ],
    [ "spinlock", "classuv_1_1spinlock.html", "classuv_1_1spinlock" ],
    [ "stream", "classuv_1_1stream.html", "classuv_1_1stream" ],
    [ "tcp", "classuv_1_1tcp.html", "classuv_1_1tcp" ],
    [ "timer", "classuv_1_1timer.html", "classuv_1_1timer" ],
    [ "tty", "classuv_1_1tty.html", "classuv_1_1tty" ],
    [ "type_at", "structuv_1_1type__at.html", null ],
    [ "type_storage", "classuv_1_1type__storage.html", "classuv_1_1type__storage" ],
    [ "udp", "classuv_1_1udp.html", "classuv_1_1udp" ],
    [ "udp_send", "classuv_1_1udp__send.html", "classuv_1_1udp__send" ],
    [ "union_storage", "classuv_1_1union__storage.html", "classuv_1_1union__storage" ],
    [ "uv_handle_traits< uv_async_t >", "structuv_1_1uv__handle__traits_3_01uv__async__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__async__t_01_4" ],
    [ "uv_handle_traits< uv_check_t >", "structuv_1_1uv__handle__traits_3_01uv__check__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__check__t_01_4" ],
    [ "uv_handle_traits< uv_fs_event_t >", "structuv_1_1uv__handle__traits_3_01uv__fs__event__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__fs__event__t_01_4" ],
    [ "uv_handle_traits< uv_fs_poll_t >", "structuv_1_1uv__handle__traits_3_01uv__fs__poll__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__fs__poll__t_01_4" ],
    [ "uv_handle_traits< uv_handle_t >", "structuv_1_1uv__handle__traits_3_01uv__handle__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__handle__t_01_4" ],
    [ "uv_handle_traits< uv_idle_t >", "structuv_1_1uv__handle__traits_3_01uv__idle__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__idle__t_01_4" ],
    [ "uv_handle_traits< uv_pipe_t >", "structuv_1_1uv__handle__traits_3_01uv__pipe__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__pipe__t_01_4" ],
    [ "uv_handle_traits< uv_poll_t >", "structuv_1_1uv__handle__traits_3_01uv__poll__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__poll__t_01_4" ],
    [ "uv_handle_traits< uv_prepare_t >", "structuv_1_1uv__handle__traits_3_01uv__prepare__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__prepare__t_01_4" ],
    [ "uv_handle_traits< uv_process_t >", "structuv_1_1uv__handle__traits_3_01uv__process__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__process__t_01_4" ],
    [ "uv_handle_traits< uv_signal_t >", "structuv_1_1uv__handle__traits_3_01uv__signal__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__signal__t_01_4" ],
    [ "uv_handle_traits< uv_stream_t >", "structuv_1_1uv__handle__traits_3_01uv__stream__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__stream__t_01_4" ],
    [ "uv_handle_traits< uv_tcp_t >", "structuv_1_1uv__handle__traits_3_01uv__tcp__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__tcp__t_01_4" ],
    [ "uv_handle_traits< uv_timer_t >", "structuv_1_1uv__handle__traits_3_01uv__timer__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__timer__t_01_4" ],
    [ "uv_handle_traits< uv_tty_t >", "structuv_1_1uv__handle__traits_3_01uv__tty__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__tty__t_01_4" ],
    [ "uv_handle_traits< uv_udp_t >", "structuv_1_1uv__handle__traits_3_01uv__udp__t_01_4.html", "structuv_1_1uv__handle__traits_3_01uv__udp__t_01_4" ],
    [ "uv_req_traits< uv_connect_t >", "structuv_1_1uv__req__traits_3_01uv__connect__t_01_4.html", "structuv_1_1uv__req__traits_3_01uv__connect__t_01_4" ],
    [ "uv_req_traits< uv_fs_t >", "structuv_1_1uv__req__traits_3_01uv__fs__t_01_4.html", "structuv_1_1uv__req__traits_3_01uv__fs__t_01_4" ],
    [ "uv_req_traits< uv_getaddrinfo_t >", "structuv_1_1uv__req__traits_3_01uv__getaddrinfo__t_01_4.html", "structuv_1_1uv__req__traits_3_01uv__getaddrinfo__t_01_4" ],
    [ "uv_req_traits< uv_getnameinfo_t >", "structuv_1_1uv__req__traits_3_01uv__getnameinfo__t_01_4.html", "structuv_1_1uv__req__traits_3_01uv__getnameinfo__t_01_4" ],
    [ "uv_req_traits< uv_req_t >", "structuv_1_1uv__req__traits_3_01uv__req__t_01_4.html", "structuv_1_1uv__req__traits_3_01uv__req__t_01_4" ],
    [ "uv_req_traits< uv_shutdown_t >", "structuv_1_1uv__req__traits_3_01uv__shutdown__t_01_4.html", "structuv_1_1uv__req__traits_3_01uv__shutdown__t_01_4" ],
    [ "uv_req_traits< uv_udp_send_t >", "structuv_1_1uv__req__traits_3_01uv__udp__send__t_01_4.html", "structuv_1_1uv__req__traits_3_01uv__udp__send__t_01_4" ],
    [ "uv_req_traits< uv_work_t >", "structuv_1_1uv__req__traits_3_01uv__work__t_01_4.html", "structuv_1_1uv__req__traits_3_01uv__work__t_01_4" ],
    [ "uv_req_traits< uv_write_t >", "structuv_1_1uv__req__traits_3_01uv__write__t_01_4.html", "structuv_1_1uv__req__traits_3_01uv__write__t_01_4" ],
    [ "work", "classuv_1_1work.html", "classuv_1_1work" ],
    [ "write", "classuv_1_1write.html", "classuv_1_1write" ]
];