var searchData=
[
  ['u16streampos',['u16streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u16string',['u16string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['u32streampos',['u32streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u32string',['u32string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['udp',['udp',['../classuv_1_1udp.html',1,'uv']]],
  ['udp_5fsend',['udp_send',['../classuv_1_1udp__send.html',1,'uv']]],
  ['uint16_5ft',['uint16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint32_5ft',['uint32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint64_5ft',['uint64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint8_5ft',['uint8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast16_5ft',['uint_fast16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast32_5ft',['uint_fast32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast64_5ft',['uint_fast64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast8_5ft',['uint_fast8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast16_5ft',['uint_least16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast32_5ft',['uint_least32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast64_5ft',['uint_least64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast8_5ft',['uint_least8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintmax_5ft',['uintmax_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintptr_5ft',['uintptr_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['unary_5ffunction',['unary_function',['http://en.cppreference.com/w/cpp/utility/functional/unary_function.html',1,'std']]],
  ['unary_5fnegate',['unary_negate',['http://en.cppreference.com/w/cpp/utility/functional/unary_negate.html',1,'std']]],
  ['underflow_5ferror',['underflow_error',['http://en.cppreference.com/w/cpp/error/underflow_error.html',1,'std']]],
  ['underlying_5ftype',['underlying_type',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['unexpected_5fhandler',['unexpected_handler',['http://en.cppreference.com/w/cpp/error/unexpected_handler.html',1,'std']]],
  ['uniform_5fint_5fdistribution',['uniform_int_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution.html',1,'std']]],
  ['uniform_5freal_5fdistribution',['uniform_real_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution.html',1,'std']]],
  ['union_5fstorage',['union_storage',['../classuv_1_1union__storage.html',1,'uv']]],
  ['unique_5flock',['unique_lock',['http://en.cppreference.com/w/cpp/thread/unique_lock.html',1,'std']]],
  ['unique_5fptr',['unique_ptr',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unlink',['unlink',['../classuv_1_1fs_1_1unlink.html',1,'uv::fs']]],
  ['unordered_5fmap',['unordered_map',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmultimap',['unordered_multimap',['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std']]],
  ['unordered_5fmultiset',['unordered_multiset',['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std']]],
  ['unordered_5fset',['unordered_set',['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std']]],
  ['uses_5fallocator',['uses_allocator',['http://en.cppreference.com/w/cpp/memory/uses_allocator.html',1,'std']]],
  ['utime',['utime',['../classuv_1_1fs_1_1utime.html',1,'uv::fs']]],
  ['uv_5fbuf',['uv_buf',['../structuv_1_1buffer_1_1instance_1_1uv__buf.html',1,'uv::buffer::instance']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fasync_5ft_20_3e',['uv_handle_traits&lt; uv_async_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__async__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fcheck_5ft_20_3e',['uv_handle_traits&lt; uv_check_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__check__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5ffs_5fevent_5ft_20_3e',['uv_handle_traits&lt; uv_fs_event_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__fs__event__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5ffs_5fpoll_5ft_20_3e',['uv_handle_traits&lt; uv_fs_poll_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__fs__poll__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fhandle_5ft_20_3e',['uv_handle_traits&lt; uv_handle_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__handle__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fidle_5ft_20_3e',['uv_handle_traits&lt; uv_idle_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__idle__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fpipe_5ft_20_3e',['uv_handle_traits&lt; uv_pipe_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__pipe__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fpoll_5ft_20_3e',['uv_handle_traits&lt; uv_poll_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__poll__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fprepare_5ft_20_3e',['uv_handle_traits&lt; uv_prepare_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__prepare__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fprocess_5ft_20_3e',['uv_handle_traits&lt; uv_process_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__process__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fsignal_5ft_20_3e',['uv_handle_traits&lt; uv_signal_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__signal__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fstream_5ft_20_3e',['uv_handle_traits&lt; uv_stream_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__stream__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5ftcp_5ft_20_3e',['uv_handle_traits&lt; uv_tcp_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__tcp__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5ftimer_5ft_20_3e',['uv_handle_traits&lt; uv_timer_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__timer__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5ftty_5ft_20_3e',['uv_handle_traits&lt; uv_tty_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__tty__t_01_4.html',1,'uv']]],
  ['uv_5fhandle_5ftraits_3c_20uv_5fudp_5ft_20_3e',['uv_handle_traits&lt; uv_udp_t &gt;',['../structuv_1_1uv__handle__traits_3_01uv__udp__t_01_4.html',1,'uv']]],
  ['uv_5freq_5ftraits_3c_20uv_5fconnect_5ft_20_3e',['uv_req_traits&lt; uv_connect_t &gt;',['../structuv_1_1uv__req__traits_3_01uv__connect__t_01_4.html',1,'uv']]],
  ['uv_5freq_5ftraits_3c_20uv_5ffs_5ft_20_3e',['uv_req_traits&lt; uv_fs_t &gt;',['../structuv_1_1uv__req__traits_3_01uv__fs__t_01_4.html',1,'uv']]],
  ['uv_5freq_5ftraits_3c_20uv_5fgetaddrinfo_5ft_20_3e',['uv_req_traits&lt; uv_getaddrinfo_t &gt;',['../structuv_1_1uv__req__traits_3_01uv__getaddrinfo__t_01_4.html',1,'uv']]],
  ['uv_5freq_5ftraits_3c_20uv_5fgetnameinfo_5ft_20_3e',['uv_req_traits&lt; uv_getnameinfo_t &gt;',['../structuv_1_1uv__req__traits_3_01uv__getnameinfo__t_01_4.html',1,'uv']]],
  ['uv_5freq_5ftraits_3c_20uv_5freq_5ft_20_3e',['uv_req_traits&lt; uv_req_t &gt;',['../structuv_1_1uv__req__traits_3_01uv__req__t_01_4.html',1,'uv']]],
  ['uv_5freq_5ftraits_3c_20uv_5fshutdown_5ft_20_3e',['uv_req_traits&lt; uv_shutdown_t &gt;',['../structuv_1_1uv__req__traits_3_01uv__shutdown__t_01_4.html',1,'uv']]],
  ['uv_5freq_5ftraits_3c_20uv_5fudp_5fsend_5ft_20_3e',['uv_req_traits&lt; uv_udp_send_t &gt;',['../structuv_1_1uv__req__traits_3_01uv__udp__send__t_01_4.html',1,'uv']]],
  ['uv_5freq_5ftraits_3c_20uv_5fwork_5ft_20_3e',['uv_req_traits&lt; uv_work_t &gt;',['../structuv_1_1uv__req__traits_3_01uv__work__t_01_4.html',1,'uv']]],
  ['uv_5freq_5ftraits_3c_20uv_5fwrite_5ft_20_3e',['uv_req_traits&lt; uv_write_t &gt;',['../structuv_1_1uv__req__traits_3_01uv__write__t_01_4.html',1,'uv']]]
];
